Improve permission middleare
spatie/laravel-permission pull request #2177
Opened 2022-09-14 15:19 UTC by cesarMtorres

using canany instead foreach
and other improve
is posible this change???

2022-09-14 19:53 UTC, fredsal commented
> using canany instead foreach

`canany`  Yes, 
but using route's name as permission, Not
 `$permission = $request->route()->getName();`

2022-10-12 15:52 UTC, drbyte requested changes

2022-10-12 15:52 UTC, drbyte commented on .github/workflows/main.yml
> +
This `.github/workflows/main.yml` file you added doesn't seem relevant. Please remove.

2022-10-19 00:34 UTC, drbyte commented
@cesarMtorres Thanks for the contribution.

Unfortunately `canany()` only works since Laravel 8.  This package is currently still compatible with Laravel 6 and 7.

We may consider your change for a future version which drops support for L6 and L7.

2022-10-19 02:25 UTC, closed without merging

2022-10-19 13:43 UTC, cesarMtorres commented
@drbyte thanks for the feedback

2023-04-07 20:05 UTC, drbyte commented
@cesarMtorres FYI your `canany` change has been implemented in the upcoming v6